### ISSUE TITLE
Can you provide us with your predicted structure from using AFcluster?

### ISSUE THREAD

**Issue by real-junjiezhang** [porterll/AF2_benchmark#2]
By the way, what does sub0, sub1, sub2 in AFcuster folder mean? Thanks so much .

**Comment by porterll** [comment]
We grouped the MSAs into subdirectories since there were so many.  So sub0 has some subdirectories, sub1 has others, and so on. Note that these subdirectories contain MSAs only.  These MSAs were used to generate >200,000 structures.  That's too many to post on GitHub.  Contact me directly to discuss other solutions.

**Comment by real-junjiezhang** [comment]
> We grouped the MSAs into subdirectories since there were so many. So sub0 has some subdirectories, sub1 has others, and so on. Note that these subdirectories contain MSAs only. These MSAs were used to generate >200,000 structures. That's too many to post on GitHub. Contact me directly to discuss other solutions.

Thanks for your quick reply! Can you only publish the structure of cases that were only successfully predicted by AFcluster?（Cases that can be predicted by afcluster with two folds). I would like to test my model with these structures and MSA, thanks.

**Comment by porterll** [comment]
We are happy to provide.  Please allow 2-3 weeks.

**Comment by porterll** [comment]
These predictions have been added to the AFcluster_MSAs directory in the tar-zipped afcluster_success folders.
